"""User-selectable Ghost Chimera role profiles."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class RoleProfile:
    """A public-beta path describing what Ghost Chimera should become."""

    id: str
    name: str
    description: str
    source_scopes: tuple[str, ...]
    learning_modes: tuple[str, ...]
    dashboard_tabs: tuple[str, ...]
    eval_suites: tuple[str, ...]
    operator_outcomes: tuple[str, ...] = ()
    personalization_sources: tuple[str, ...] = ()
    tool_domains: tuple[str, ...] = ()
    requires_disclosure: bool = True

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "source_scopes": list(self.source_scopes),
            "learning_modes": list(self.learning_modes),
            "dashboard_tabs": list(self.dashboard_tabs),
            "eval_suites": list(self.eval_suites),
            "operator_outcomes": list(self.operator_outcomes),
            "personalization_sources": list(self.personalization_sources),
            "tool_domains": list(self.tool_domains),
            "requires_disclosure": self.requires_disclosure,
        }


_PROFILES: dict[str, RoleProfile] = {
    "autonomous-engineer": RoleProfile(
        id="autonomous-engineer",
        name="Autonomous Engineer",
        description="Turns issues and objectives into tested code changes and pull requests.",
        source_scopes=("local_repository", "github_private_repositories", "project_docs"),
        learning_modes=("rag", "workflow_memory"),
        dashboard_tabs=("github", "review", "capabilities", "autonomy"),
        eval_suites=("github-connected", "competitive", "safety"),
        operator_outcomes=("tested code changes", "pull requests", "release-gate reports"),
        personalization_sources=("local_repository", "project_docs", "engineering_preferences"),
        tool_domains=("code_execution", "github", "review", "release_validation"),
    ),
    "ai-engineer-proxy": RoleProfile(
        id="ai-engineer-proxy",
        name="AI Engineer Proxy",
        description="Learns the user's AI engineering preferences and acts as an authorized engineering proxy.",
        source_scopes=(
            "local_machine",
            "email",
            "github_private_repositories",
            "github_public_repositories",
            "license_allowed_external_sources",
        ),
        learning_modes=("rag", "dataset_generation", "local_fine_tuning"),
        dashboard_tabs=("path", "minimind", "github", "training", "review", "audit"),
        eval_suites=("github-connected", "personal-context", "redteam", "safety"),
        operator_outcomes=("engineering proxy work", "code reviews", "agent workflow implementation"),
        personalization_sources=("local_machine", "email", "private_repositories", "public_repositories"),
        tool_domains=("code_execution", "github", "mcp", "desktop", "review"),
        requires_disclosure=True,
    ),
    "manager-operator": RoleProfile(
        id="manager-operator",
        name="Manager Operator",
        description="Coordinates decisions, follow-ups, summaries, plans, and team operations from approved work context.",
        source_scopes=("local_documents", "email", "calendar_exports", "approved_integrations", "policy_docs"),
        learning_modes=("rag", "workflow_memory", "dataset_generation"),
        dashboard_tabs=("path", "minimind", "autonomy", "audit", "memory"),
        eval_suites=("personal-context", "safety", "redteam"),
        operator_outcomes=("meeting briefs", "follow-up plans", "status summaries", "decision logs"),
        personalization_sources=("email", "calendar_exports", "team_docs", "meeting_notes", "management_preferences"),
        tool_domains=("team_coordination", "planning", "communication", "task_followup"),
    ),
    "marketing-specialist": RoleProfile(
        id="marketing-specialist",
        name="Marketing Specialist",
        description="Learns brand, audience, campaigns, and approved assets to draft, review, and coordinate marketing work.",
        source_scopes=("local_documents", "campaign_assets", "approved_public_sources", "approved_integrations"),
        learning_modes=("rag", "workflow_memory", "dataset_generation"),
        dashboard_tabs=("path", "minimind", "memory", "browser", "audit"),
        eval_suites=("personal-context", "safety"),
        operator_outcomes=("campaign briefs", "content drafts", "audience research", "brand-consistent reviews"),
        personalization_sources=("campaign_assets", "brand_guidelines", "audience_research", "content_history"),
        tool_domains=("content_operations", "research", "asset_review", "publishing_workflow"),
    ),
    "virtual-assistant": RoleProfile(
        id="virtual-assistant",
        name="Virtual Assistant",
        description="Handles consented admin, scheduling, inbox triage, reminders, and personal operations workflows.",
        source_scopes=("local_machine", "email", "calendar_exports", "approved_integrations"),
        learning_modes=("rag", "workflow_memory", "dataset_generation"),
        dashboard_tabs=("path", "minimind", "autonomy", "audit", "memory"),
        eval_suites=("personal-context", "safety", "redteam"),
        operator_outcomes=("inbox triage", "schedule prep", "reminders", "personal task execution"),
        personalization_sources=("email", "schedule_exports", "local_documents", "assistant_preferences"),
        tool_domains=("personal_admin", "calendar", "communication", "local_file_workflows"),
        requires_disclosure=True,
    ),
    "personal-operations": RoleProfile(
        id="personal-operations",
        name="Personal Operations Assistant",
        description="Finds and executes consented personal work from local context, email, and schedules.",
        source_scopes=("local_machine", "email", "calendar_exports", "approved_integrations"),
        learning_modes=("rag", "workflow_memory"),
        dashboard_tabs=("path", "minimind", "autonomy", "audit"),
        eval_suites=("personal-context", "safety"),
        operator_outcomes=("personal task discovery", "consented workflow execution", "local context summaries"),
        personalization_sources=("local_machine", "email", "calendar_exports", "personal_preferences"),
        tool_domains=("personal_admin", "local_file_workflows", "communication", "scheduling"),
    ),
    "research-analyst": RoleProfile(
        id="research-analyst",
        name="Research Analyst",
        description="Builds sourced research briefs from approved repositories, documents, and public sources.",
        source_scopes=("approved_public_sources", "github_public_repositories", "local_documents"),
        learning_modes=("rag", "dataset_generation"),
        dashboard_tabs=("path", "browser", "memory", "audit"),
        eval_suites=("smoke", "safety"),
        operator_outcomes=("sourced briefs", "evidence maps", "research summaries"),
        personalization_sources=("local_documents", "approved_public_sources", "research_preferences"),
        tool_domains=("research", "browser", "citation_review"),
    ),
    "enterprise-operator": RoleProfile(
        id="enterprise-operator",
        name="Enterprise Operator",
        description="Runs governed automations with RBAC, policy simulation, audit trails, and approval workflows.",
        source_scopes=("organization_repositories", "approved_integrations", "policy_docs"),
        learning_modes=("rag", "workflow_memory"),
        dashboard_tabs=("policy", "github", "audit", "autonomy", "capabilities"),
        eval_suites=("safety", "redteam", "github-connected"),
        operator_outcomes=("governed automations", "approval workflows", "audit-ready operations"),
        personalization_sources=("policy_docs", "organization_repositories", "approved_integrations"),
        tool_domains=("governance", "github", "policy_simulation", "audit"),
    ),
    "custom": RoleProfile(
        id="custom",
        name="Custom Ghost",
        description="Lets the operator combine source, learning, tool, and policy controls manually.",
        source_scopes=("operator_selected",),
        learning_modes=("rag", "workflow_memory"),
        dashboard_tabs=("path", "autonomy", "memory", "audit"),
        eval_suites=("safety",),
        operator_outcomes=("operator-defined work",),
        personalization_sources=("operator_selected",),
        tool_domains=("operator_selected",),
    ),
}


_EXTRA_PROFILE_SPECS: tuple[dict[str, Any], ...] = (
    {
        "id": "customer-support-operator",
        "name": "Customer Support Operator",
        "description": "Triage tickets, draft replies, detect escalations, and maintain support knowledge.",
        "outcomes": ("ticket triage", "reply drafts", "escalation summaries"),
        "sources": ("support_docs", "ticket_exports", "approved_integrations"),
        "domains": ("customer_support", "knowledge_base", "communication"),
    },
    {
        "id": "sales-development-rep",
        "name": "Sales Development Rep",
        "description": "Research accounts, qualify leads, and draft compliant outreach sequences.",
        "outcomes": ("lead research", "qualification notes", "outreach drafts"),
        "sources": ("crm_exports", "approved_public_sources", "sales_playbooks"),
        "domains": ("sales_ops", "crm", "research"),
    },
    {
        "id": "account-executive",
        "name": "Account Executive",
        "description": "Prepare deal briefs, objection handling, follow-ups, and buyer-specific notes.",
        "outcomes": ("deal briefs", "follow-up plans", "proposal outlines"),
        "sources": ("crm_exports", "sales_playbooks", "approved_integrations"),
        "domains": ("sales_ops", "communication", "proposal_workflow"),
    },
    {
        "id": "customer-success-manager",
        "name": "Customer Success Manager",
        "description": "Track account health, renewal risks, usage signals, and customer action plans.",
        "outcomes": ("health summaries", "renewal risk reports", "success plans"),
        "sources": ("crm_exports", "support_docs", "approved_integrations"),
        "domains": ("customer_success", "account_health", "communication"),
    },
    {
        "id": "hr-recruiter",
        "name": "HR Recruiter",
        "description": "Screen candidates, build interview plans, and coordinate hiring workflows.",
        "outcomes": ("candidate summaries", "interview kits", "hiring follow-ups"),
        "sources": ("job_descriptions", "resume_exports", "approved_integrations"),
        "domains": ("recruiting", "hr_ops", "communication"),
    },
    {
        "id": "hr-operations",
        "name": "HR Operations",
        "description": "Handle onboarding, policy answers, internal requests, and HR process checklists.",
        "outcomes": ("onboarding plans", "policy summaries", "request routing"),
        "sources": ("policy_docs", "employee_handbook", "approved_integrations"),
        "domains": ("hr_ops", "policy_review", "workflow_checklists"),
    },
    {
        "id": "finance-analyst",
        "name": "Finance Analyst",
        "description": "Analyze budgets, forecasts, spend patterns, and financial operating metrics.",
        "outcomes": ("budget summaries", "variance notes", "forecast assumptions"),
        "sources": ("finance_exports", "local_documents", "approved_integrations"),
        "domains": ("finance", "analysis", "reporting"),
        "redteam": True,
    },
    {
        "id": "bookkeeping-assistant",
        "name": "Bookkeeping Assistant",
        "description": "Categorize transactions, prepare reconciliation notes, and flag exceptions.",
        "outcomes": ("transaction categories", "reconciliation notes", "exception lists"),
        "sources": ("finance_exports", "receipt_exports", "approved_integrations"),
        "domains": ("bookkeeping", "finance", "exception_review"),
        "redteam": True,
    },
    {
        "id": "trader-path",
        "name": "Trader Path",
        "description": "Plan and execute supervised market trading workflows from approved broker and market feeds.",
        "outcomes": ("trade ideas", "risk-managed execution plans", "broker handoff checklists"),
        "sources": ("market_data_feeds", "portfolio_exports", "approved_integrations", "risk_policy_docs"),
        "domains": ("trading", "portfolio_management", "risk_management"),
        "redteam": True,
    },
    {
        "id": "crypto-trader-path",
        "name": "Crypto Trader Path",
        "description": "Operate supervised crypto trading flows with exchange data, wallet context, and compliance guardrails.",
        "outcomes": ("crypto trade plans", "position monitoring", "exchange execution playbooks"),
        "sources": ("onchain_data", "exchange_exports", "approved_integrations", "risk_policy_docs"),
        "domains": ("crypto_trading", "portfolio_management", "risk_management"),
        "redteam": True,
    },
    {
        "id": "legal-ops-assistant",
        "name": "Legal Ops Assistant",
        "description": "Organize contracts, clause checklists, intake forms, and review routing.",
        "outcomes": ("contract summaries", "clause checklists", "review routing"),
        "sources": ("contract_exports", "policy_docs", "approved_integrations"),
        "domains": ("legal_ops", "document_review", "workflow_checklists"),
        "redteam": True,
    },
    {
        "id": "compliance-monitor",
        "name": "Compliance Monitor",
        "description": "Monitor policy obligations, evidence gaps, controls, and audit readiness.",
        "outcomes": ("control checks", "evidence gaps", "audit summaries"),
        "sources": ("policy_docs", "audit_exports", "approved_integrations"),
        "domains": ("compliance", "audit", "risk_review"),
        "redteam": True,
    },
    {
        "id": "security-analyst",
        "name": "Security Analyst",
        "description": "Review alerts, detect suspicious patterns, and prepare incident evidence.",
        "outcomes": ("alert triage", "incident notes", "risk summaries"),
        "sources": ("security_exports", "policy_docs", "approved_integrations"),
        "domains": ("security", "incident_review", "audit"),
        "redteam": True,
    },
    {
        "id": "incident-commander",
        "name": "Incident Commander",
        "description": "Coordinate incident response, timelines, stakeholders, and recovery actions.",
        "outcomes": ("incident timelines", "status updates", "recovery checklists"),
        "sources": ("runbooks", "security_exports", "approved_integrations"),
        "domains": ("incident_response", "coordination", "communication"),
        "redteam": True,
    },
    {
        "id": "devops-sre",
        "name": "DevOps SRE",
        "description": "Inspect reliability signals, runbooks, deployments, and operational fixes.",
        "outcomes": ("reliability reviews", "runbook updates", "deployment notes"),
        "sources": ("local_repository", "runbooks", "approved_integrations"),
        "domains": ("devops", "sre", "release_validation"),
    },
    {
        "id": "cloud-cost-optimizer",
        "name": "Cloud Cost Optimizer",
        "description": "Analyze infrastructure spend, waste, utilization, and cost-saving actions.",
        "outcomes": ("cost summaries", "waste findings", "optimization plans"),
        "sources": ("billing_exports", "infrastructure_docs", "approved_integrations"),
        "domains": ("cloud_finops", "analysis", "reporting"),
    },
    {
        "id": "data-analyst",
        "name": "Data Analyst",
        "description": "Explore datasets, build summaries, explain trends, and prepare analysis notebooks.",
        "outcomes": ("data summaries", "trend explanations", "analysis plans"),
        "sources": ("dataset_exports", "local_documents", "approved_integrations"),
        "domains": ("data_analysis", "reporting", "visualization"),
    },
    {
        "id": "business-intelligence-analyst",
        "name": "Business Intelligence Analyst",
        "description": "Translate business questions into metrics, dashboards, and decision briefs.",
        "outcomes": ("metric definitions", "dashboard briefs", "decision summaries"),
        "sources": ("dashboard_exports", "business_docs", "approved_integrations"),
        "domains": ("business_intelligence", "metrics", "reporting"),
    },
    {
        "id": "product-manager",
        "name": "Product Manager",
        "description": "Turn feedback and strategy into roadmaps, specs, prioritization, and release notes.",
        "outcomes": ("product specs", "roadmap notes", "release briefs"),
        "sources": ("product_docs", "customer_feedback", "approved_integrations"),
        "domains": ("product_management", "planning", "communication"),
    },
    {
        "id": "project-manager",
        "name": "Project Manager",
        "description": "Track tasks, risks, milestones, blockers, and stakeholder communication.",
        "outcomes": ("project plans", "risk logs", "status updates"),
        "sources": ("project_docs", "task_exports", "approved_integrations"),
        "domains": ("project_management", "planning", "coordination"),
    },
    {
        "id": "scrum-master",
        "name": "Scrum Master",
        "description": "Prepare ceremonies, identify blockers, and maintain sprint hygiene.",
        "outcomes": ("standup summaries", "retro notes", "sprint risk lists"),
        "sources": ("task_exports", "team_docs", "approved_integrations"),
        "domains": ("agile_ops", "team_coordination", "planning"),
    },
    {
        "id": "qa-test-engineer",
        "name": "QA Test Engineer",
        "description": "Create test plans, reproduce bugs, generate cases, and report quality risks.",
        "outcomes": ("test plans", "bug repro notes", "quality reports"),
        "sources": ("local_repository", "issue_exports", "test_docs"),
        "domains": ("testing", "quality", "release_validation"),
    },
    {
        "id": "release-manager",
        "name": "Release Manager",
        "description": "Coordinate release gates, changelogs, validations, and rollback notes.",
        "outcomes": ("release checklists", "changelog drafts", "validation reports"),
        "sources": ("local_repository", "release_docs", "approved_integrations"),
        "domains": ("release_management", "release_validation", "communication"),
    },
    {
        "id": "documentation-writer",
        "name": "Documentation Writer",
        "description": "Write user docs, tutorials, guides, and operational documentation from source.",
        "outcomes": ("guides", "tutorials", "documentation updates"),
        "sources": ("local_repository", "project_docs", "approved_public_sources"),
        "domains": ("documentation", "technical_writing", "content_operations"),
    },
    {
        "id": "technical-writer",
        "name": "Technical Writer",
        "description": "Convert code and architecture into precise API docs and technical references.",
        "outcomes": ("API references", "architecture docs", "developer guides"),
        "sources": ("local_repository", "project_docs", "approved_public_sources"),
        "domains": ("technical_writing", "documentation", "architecture_review"),
    },
    {
        "id": "api-integrator",
        "name": "API Integrator",
        "description": "Read API docs, plan integrations, generate client workflows, and verify calls.",
        "outcomes": ("integration plans", "API call maps", "verification notes"),
        "sources": ("api_docs", "local_repository", "approved_public_sources"),
        "domains": ("api_integration", "code_execution", "documentation"),
    },
    {
        "id": "mcp-toolsmith",
        "name": "MCP Toolsmith",
        "description": "Design, evaluate, harden, and document Model Context Protocol tools.",
        "outcomes": ("MCP tool plans", "server audits", "capability tests"),
        "sources": ("local_repository", "github_public_repositories", "approved_public_sources"),
        "domains": ("mcp", "tooling", "security_review"),
        "redteam": True,
    },
    {
        "id": "prompt-engineer",
        "name": "Prompt Engineer",
        "description": "Design prompts, evals, guardrails, and role instructions for repeatable work.",
        "outcomes": ("prompt packs", "eval cases", "guardrail notes"),
        "sources": ("prompt_libraries", "project_docs", "approved_public_sources"),
        "domains": ("prompt_engineering", "evals", "safety"),
    },
    {
        "id": "ai-safety-reviewer",
        "name": "AI Safety Reviewer",
        "description": "Review agent behaviors, policies, prompts, and tool access for safety risks.",
        "outcomes": ("safety findings", "policy recommendations", "redteam cases"),
        "sources": ("policy_docs", "local_repository", "approved_public_sources"),
        "domains": ("ai_safety", "policy_review", "redteam"),
        "redteam": True,
    },
    {
        "id": "research-librarian",
        "name": "Research Librarian",
        "description": "Organize sources, citations, literature maps, and evidence-backed answers.",
        "outcomes": ("source maps", "citation lists", "evidence summaries"),
        "sources": ("local_documents", "approved_public_sources", "research_notes"),
        "domains": ("research", "citation_review", "knowledge_management"),
    },
    {
        "id": "academic-assistant",
        "name": "Academic Assistant",
        "description": "Support study plans, paper outlines, source summaries, and learning workflows.",
        "outcomes": ("study plans", "paper outlines", "source summaries"),
        "sources": ("local_documents", "approved_public_sources", "course_materials"),
        "domains": ("education", "research", "writing"),
    },
    {
        "id": "grant-writer",
        "name": "Grant Writer",
        "description": "Draft grant narratives, budgets, compliance notes, and submission checklists.",
        "outcomes": ("grant drafts", "budget notes", "submission checklists"),
        "sources": ("grant_docs", "organization_docs", "approved_public_sources"),
        "domains": ("grant_writing", "compliance", "writing"),
        "redteam": True,
    },
    {
        "id": "investor-relations",
        "name": "Investor Relations",
        "description": "Prepare investor updates, diligence answers, metrics summaries, and narratives.",
        "outcomes": ("investor updates", "diligence briefs", "metrics summaries"),
        "sources": ("finance_exports", "company_docs", "approved_integrations"),
        "domains": ("investor_relations", "finance", "communication"),
        "redteam": True,
    },
    {
        "id": "founder-chief-of-staff",
        "name": "Founder Chief of Staff",
        "description": "Coordinate founder priorities, operating rhythm, decisions, and follow-through.",
        "outcomes": ("priority briefs", "decision logs", "follow-up plans"),
        "sources": ("local_documents", "email", "calendar_exports", "approved_integrations"),
        "domains": ("executive_ops", "planning", "communication"),
    },
    {
        "id": "executive-assistant",
        "name": "Executive Assistant",
        "description": "Manage schedule prep, inbox triage, briefs, reminders, and admin workflows.",
        "outcomes": ("schedule briefs", "inbox triage", "admin checklists"),
        "sources": ("email", "calendar_exports", "local_documents", "approved_integrations"),
        "domains": ("personal_admin", "calendar", "communication"),
    },
    {
        "id": "operations-analyst",
        "name": "Operations Analyst",
        "description": "Track operating metrics, process gaps, bottlenecks, and improvement plans.",
        "outcomes": ("ops reports", "process maps", "improvement plans"),
        "sources": ("operations_docs", "dataset_exports", "approved_integrations"),
        "domains": ("operations", "analysis", "workflow_checklists"),
    },
    {
        "id": "procurement-agent",
        "name": "Procurement Agent",
        "description": "Compare vendors, requirements, quotes, approvals, and procurement risks.",
        "outcomes": ("vendor comparisons", "quote summaries", "approval packets"),
        "sources": ("vendor_docs", "policy_docs", "approved_integrations"),
        "domains": ("procurement", "vendor_management", "compliance"),
        "redteam": True,
    },
    {
        "id": "vendor-manager",
        "name": "Vendor Manager",
        "description": "Monitor vendor performance, contracts, renewals, and risk follow-ups.",
        "outcomes": ("vendor scorecards", "renewal notes", "risk summaries"),
        "sources": ("vendor_docs", "contract_exports", "approved_integrations"),
        "domains": ("vendor_management", "contract_review", "risk_review"),
        "redteam": True,
    },
    {
        "id": "logistics-coordinator",
        "name": "Logistics Coordinator",
        "description": "Coordinate shipments, exceptions, carrier updates, and delivery timelines.",
        "outcomes": ("shipment summaries", "exception reports", "carrier follow-ups"),
        "sources": ("logistics_exports", "carrier_docs", "approved_integrations"),
        "domains": ("logistics", "exception_review", "communication"),
    },
    {
        "id": "inventory-planner",
        "name": "Inventory Planner",
        "description": "Analyze demand, stockouts, reorder risks, and inventory planning actions.",
        "outcomes": ("inventory forecasts", "reorder notes", "stockout risks"),
        "sources": ("inventory_exports", "sales_exports", "approved_integrations"),
        "domains": ("inventory_planning", "analysis", "operations"),
    },
    {
        "id": "ecommerce-operator",
        "name": "Ecommerce Operator",
        "description": "Maintain listings, promotions, support signals, fulfillment issues, and analytics.",
        "outcomes": ("listing updates", "promotion briefs", "fulfillment issue lists"),
        "sources": ("store_exports", "campaign_assets", "approved_integrations"),
        "domains": ("ecommerce", "content_operations", "operations"),
    },
    {
        "id": "content-editor",
        "name": "Content Editor",
        "description": "Review drafts, enforce style, plan calendars, and prepare publish-ready content.",
        "outcomes": ("edited drafts", "content calendars", "style notes"),
        "sources": ("content_history", "brand_guidelines", "approved_public_sources"),
        "domains": ("content_operations", "editing", "publishing_workflow"),
    },
    {
        "id": "social-media-manager",
        "name": "Social Media Manager",
        "description": "Plan posts, adapt campaigns, review engagement, and manage publishing queues.",
        "outcomes": ("post drafts", "content calendars", "engagement summaries"),
        "sources": ("campaign_assets", "brand_guidelines", "approved_integrations"),
        "domains": ("social_media", "content_operations", "publishing_workflow"),
    },
    {
        "id": "seo-specialist",
        "name": "SEO Specialist",
        "description": "Research keywords, content gaps, technical issues, and search-intent briefs.",
        "outcomes": ("keyword maps", "content briefs", "technical SEO notes"),
        "sources": ("analytics_exports", "approved_public_sources", "website_docs"),
        "domains": ("seo", "research", "content_operations"),
    },
    {
        "id": "community-manager",
        "name": "Community Manager",
        "description": "Summarize community signals, answer patterns, moderation needs, and campaigns.",
        "outcomes": ("community summaries", "moderation notes", "campaign ideas"),
        "sources": ("community_exports", "brand_guidelines", "approved_integrations"),
        "domains": ("community_ops", "communication", "content_operations"),
    },
    {
        "id": "course-creator",
        "name": "Course Creator",
        "description": "Convert expertise into lessons, exercises, assessments, and learning paths.",
        "outcomes": ("lesson outlines", "exercises", "assessment drafts"),
        "sources": ("course_materials", "local_documents", "approved_public_sources"),
        "domains": ("education", "content_operations", "writing"),
    },
    {
        "id": "tutor-coach",
        "name": "Tutor Coach",
        "description": "Personalize explanations, practice plans, learning feedback, and progress checks.",
        "outcomes": ("practice plans", "feedback summaries", "learning checkpoints"),
        "sources": ("course_materials", "local_documents", "learning_preferences"),
        "domains": ("education", "coaching", "personalization"),
    },
    {
        "id": "real-estate-assistant",
        "name": "Real Estate Assistant",
        "description": "Compare listings, prepare client briefs, schedule follow-ups, and summarize market data.",
        "outcomes": ("listing comparisons", "client briefs", "market notes"),
        "sources": ("listing_exports", "client_notes", "approved_public_sources"),
        "domains": ("real_estate", "research", "communication"),
    },
    {
        "id": "healthcare-admin-assistant",
        "name": "Healthcare Admin Assistant",
        "description": "Support non-clinical scheduling, intake summaries, and administrative follow-ups.",
        "outcomes": ("intake summaries", "schedule notes", "admin checklists"),
        "sources": ("admin_exports", "policy_docs", "approved_integrations"),
        "domains": ("healthcare_admin", "scheduling", "communication"),
        "redteam": True,
    },
    {
        "id": "medical-coding-assistant",
        "name": "Medical Coding Assistant",
        "description": "Prepare coding-support notes and exception lists for human review.",
        "outcomes": ("coding notes", "exception lists", "review packets"),
        "sources": ("coding_guides", "admin_exports", "approved_public_sources"),
        "domains": ("medical_admin", "compliance", "document_review"),
        "redteam": True,
    },
    {
        "id": "insurance-claims-assistant",
        "name": "Insurance Claims Assistant",
        "description": "Summarize claims, identify missing evidence, and prepare review packets.",
        "outcomes": ("claim summaries", "evidence gaps", "review packets"),
        "sources": ("claims_exports", "policy_docs", "approved_integrations"),
        "domains": ("insurance", "document_review", "compliance"),
        "redteam": True,
    },
    {
        "id": "travel-planner",
        "name": "Travel Planner",
        "description": "Build itineraries, compare constraints, track bookings, and prepare trip briefs.",
        "outcomes": ("itineraries", "booking checklists", "trip briefs"),
        "sources": ("travel_docs", "email", "approved_public_sources"),
        "domains": ("travel_planning", "personal_admin", "research"),
    },
    {
        "id": "event-planner",
        "name": "Event Planner",
        "description": "Coordinate vendors, schedules, guest lists, logistics, and run-of-show plans.",
        "outcomes": ("event timelines", "vendor lists", "run-of-show plans"),
        "sources": ("event_docs", "vendor_docs", "approved_integrations"),
        "domains": ("event_planning", "vendor_management", "coordination"),
    },
    {
        "id": "personal-finance-coach",
        "name": "Personal Finance Coach",
        "description": "Summarize budgets, goals, savings plans, and financial habits for human decisions.",
        "outcomes": ("budget summaries", "savings plans", "habit reviews"),
        "sources": ("finance_exports", "local_documents", "approved_integrations"),
        "domains": ("personal_finance", "coaching", "analysis"),
        "redteam": True,
    },
    {
        "id": "tax-prep-assistant",
        "name": "Tax Prep Assistant",
        "description": "Organize tax documents, deductions, questions, and preparer-ready packets.",
        "outcomes": ("tax checklists", "document packets", "question lists"),
        "sources": ("tax_docs", "finance_exports", "approved_integrations"),
        "domains": ("tax_admin", "document_review", "compliance"),
        "redteam": True,
    },
    {
        "id": "recruiting-sourcer",
        "name": "Recruiting Sourcer",
        "description": "Build candidate searches, role maps, outreach notes, and talent pipelines.",
        "outcomes": ("candidate lists", "role maps", "outreach notes"),
        "sources": ("job_descriptions", "approved_public_sources", "approved_integrations"),
        "domains": ("recruiting", "research", "communication"),
    },
    {
        "id": "ux-researcher",
        "name": "UX Researcher",
        "description": "Synthesize interviews, feedback, usability findings, and research plans.",
        "outcomes": ("research plans", "insight summaries", "usability findings"),
        "sources": ("research_notes", "customer_feedback", "approved_integrations"),
        "domains": ("ux_research", "research", "product_management"),
    },
    {
        "id": "design-ops-assistant",
        "name": "Design Ops Assistant",
        "description": "Maintain design process docs, critique queues, asset reviews, and handoff checklists.",
        "outcomes": ("handoff checklists", "asset reviews", "process notes"),
        "sources": ("design_docs", "campaign_assets", "approved_integrations"),
        "domains": ("design_ops", "asset_review", "workflow_checklists"),
    },
    {
        "id": "localization-manager",
        "name": "Localization Manager",
        "description": "Coordinate translation workflows, terminology, locale QA, and launch readiness.",
        "outcomes": ("locale checklists", "terminology notes", "translation briefs"),
        "sources": ("localization_assets", "brand_guidelines", "approved_integrations"),
        "domains": ("localization", "quality", "content_operations"),
    },
    {
        "id": "data-privacy-officer",
        "name": "Data Privacy Officer",
        "description": "Track privacy obligations, data maps, DPIA notes, and request workflows.",
        "outcomes": ("privacy reviews", "data maps", "request checklists"),
        "sources": ("policy_docs", "data_maps", "approved_integrations"),
        "domains": ("privacy", "compliance", "risk_review"),
        "redteam": True,
    },
    {
        "id": "risk-analyst",
        "name": "Risk Analyst",
        "description": "Identify operational, vendor, financial, and security risks with evidence.",
        "outcomes": ("risk registers", "mitigation plans", "evidence summaries"),
        "sources": ("risk_docs", "audit_exports", "approved_integrations"),
        "domains": ("risk_review", "analysis", "compliance"),
        "redteam": True,
    },
    {
        "id": "knowledge-manager",
        "name": "Knowledge Manager",
        "description": "Curate internal knowledge, detect stale docs, and route missing answers.",
        "outcomes": ("knowledge maps", "stale-doc reports", "answer routing"),
        "sources": ("local_documents", "team_docs", "approved_integrations"),
        "domains": ("knowledge_management", "documentation", "workflow_checklists"),
    },
    {
        "id": "crm-operator",
        "name": "CRM Operator",
        "description": "Clean records, summarize pipeline, route follow-ups, and maintain CRM hygiene.",
        "outcomes": ("CRM hygiene reports", "pipeline summaries", "follow-up queues"),
        "sources": ("crm_exports", "approved_integrations", "sales_playbooks"),
        "domains": ("crm", "sales_ops", "operations"),
    },
)


def _build_extra_profile(spec: dict[str, Any]) -> RoleProfile:
    eval_suites = ["personal-context", "safety"]
    if spec.get("redteam"):
        eval_suites.append("redteam")
    tabs = ["path", "minimind", "memory", "autonomy", "audit"]
    domains = tuple(spec["domains"])
    if any(domain in domains for domain in ("devops", "sre", "mcp", "testing", "release_management")):
        tabs.append("github")
    return RoleProfile(
        id=str(spec["id"]),
        name=str(spec["name"]),
        description=str(spec["description"]),
        source_scopes=tuple(spec["sources"]),
        learning_modes=("rag", "workflow_memory", "dataset_generation"),
        dashboard_tabs=tuple(dict.fromkeys(tabs)),
        eval_suites=tuple(eval_suites),
        operator_outcomes=tuple(spec["outcomes"]),
        personalization_sources=tuple(spec["sources"]),
        tool_domains=domains,
    )


_PROFILES.update({spec["id"]: _build_extra_profile(spec) for spec in _EXTRA_PROFILE_SPECS})


def list_role_profiles() -> list[RoleProfile]:
    """Return all built-in public-beta Ghost paths."""

    return list(_PROFILES.values())


def get_role_profile(profile_id: str) -> RoleProfile:
    """Return one built-in Ghost path by id."""

    try:
        return _PROFILES[profile_id]
    except KeyError as exc:
        raise ValueError(f"Unknown role profile: {profile_id}") from exc
