#!/usr/bin/env python3
"""Test Coverage Reporter for Ghost Chimera

Analyzes source files and identifies modules without corresponding tests.
Part of IBM Bob's delivery accelerator backlog.

Usage:
    python scripts/coverage_report.py
    python scripts/coverage_report.py --format markdown
    python scripts/coverage_report.py --output coverage_report.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
GHOSTCHIMERA_DIR = ROOT / "ghostchimera"
TESTS_DIR = ROOT / "tests"


def find_source_modules() -> list[Path]:
    """Find all Python source modules in ghostchimera/."""
    modules = []
    for py_file in GHOSTCHIMERA_DIR.rglob("*.py"):
        if "__pycache__" in str(py_file):
            continue
        if py_file.name == "__init__.py":
            continue
        modules.append(py_file)
    return sorted(modules)


def find_test_files() -> dict[str, Path]:
    """Find all test files and map them to module names."""
    test_map = {}
    for test_file in TESTS_DIR.rglob("test_*.py"):
        # Extract module name from test file
        module_name = test_file.stem.replace("test_", "")
        test_map[module_name] = test_file
    return test_map


def analyze_coverage() -> dict[str, Any]:
    """Analyze test coverage."""
    source_modules = find_source_modules()
    test_map = find_test_files()

    tested = []
    untested = []

    for source_file in source_modules:
        module_name = source_file.stem
        rel_path = source_file.relative_to(ROOT)

        if module_name in test_map:
            tested.append(
                {
                    "module": module_name,
                    "source": str(rel_path),
                    "test": str(test_map[module_name].relative_to(ROOT)),
                }
            )
        else:
            untested.append(
                {
                    "module": module_name,
                    "source": str(rel_path),
                }
            )

    total = len(source_modules)
    tested_count = len(tested)
    coverage_ratio = tested_count / total if total > 0 else 0

    return {
        "total_modules": total,
        "tested_count": tested_count,
        "untested_count": len(untested),
        "coverage_ratio": coverage_ratio,
        "tested": tested,
        "untested": untested,
    }


def format_text_report(data: dict) -> str:
    """Format coverage data as text report."""
    lines = []
    lines.append("=" * 80)
    lines.append("Ghost Chimera Test Coverage Report")
    lines.append("=" * 80)
    lines.append("")
    lines.append(f"Total Source Modules: {data['total_modules']}")
    lines.append(f"Tested Modules: {data['tested_count']}")
    lines.append(f"Untested Modules: {data['untested_count']}")
    lines.append(f"Coverage Ratio: {data['coverage_ratio']:.1%}")
    lines.append("")

    if data["untested"]:
        lines.append("## Untested Modules")
        lines.append("")
        for item in data["untested"]:
            lines.append(f"  - {item['source']}")
        lines.append("")

    lines.append("## Recommendations")
    lines.append("")
    if data["coverage_ratio"] < 0.8:
        lines.append("  WARNING: Coverage is below 80%. Consider adding tests for untested modules.")
    else:
        lines.append("  OK: Coverage is good (>80%).")
    lines.append("")
    lines.append("Run with --format markdown to generate a report for documentation.")
    lines.append("=" * 80)

    return "\n".join(lines)


def format_markdown_report(data: dict) -> str:
    """Format coverage data as markdown report."""
    lines = []
    lines.append("# Test Coverage Report")
    lines.append("")
    lines.append("**Generated by:** IBM Bob Coverage Reporter")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total Source Modules:** {data['total_modules']}")
    lines.append(f"- **Tested Modules:** {data['tested_count']}")
    lines.append(f"- **Untested Modules:** {data['untested_count']}")
    lines.append(f"- **Coverage Ratio:** {data['coverage_ratio']:.1%}")
    lines.append("")

    if data["untested"]:
        lines.append("## Untested Modules")
        lines.append("")
        lines.append("The following modules do not have corresponding test files:")
        lines.append("")
        for item in data["untested"]:
            lines.append(f"- `{item['source']}`")
        lines.append("")

    lines.append("## Recommendations")
    lines.append("")
    if data["coverage_ratio"] < 0.8:
        lines.append("**Action Required:** Coverage is below 80%. Consider adding tests for untested modules.")
    else:
        lines.append("**Good Coverage:** Coverage is above 80%.")
    lines.append("")
    lines.append("## Next Steps")
    lines.append("")
    lines.append("1. Review untested modules and prioritize based on criticality")
    lines.append("2. Use `scripts/generate_test_scaffold.py` to create test templates")
    lines.append("3. Run `python -m pytest tests/ -v` to verify new tests")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Test Coverage Reporter for Ghost Chimera",
    )
    parser.add_argument(
        "--format",
        choices=["text", "markdown"],
        default="text",
        help="Output format (default: text)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Write report to file instead of stdout",
    )
    parser.add_argument(
        "--fail-under",
        type=float,
        default=None,
        help="Exit with code 1 if the coverage ratio is below this percentage.",
    )

    args = parser.parse_args()

    data = analyze_coverage()

    report = format_markdown_report(data) if args.format == "markdown" else format_text_report(data)

    if args.output:
        args.output.write_text(report, encoding="utf-8")
        print(f"Report written to {args.output}")
    else:
        print(report)

    if args.fail_under is not None and data["coverage_ratio"] < (args.fail_under / 100):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())

# Made with Bob
