"""
Intelligent Test Scaffold Generator for Ghost Chimera.

Generates pytest-style test scaffolds from Python source files using AST analysis.
Part of IBM Bob Phase 2: Testing Infrastructure.
"""

import argparse
import ast
import sys
from pathlib import Path
from typing import Any

# Add project root to path
ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))


def analyze_source_file(source_path: Path) -> dict[str, Any]:
    """
    Analyze a Python source file and extract public functions and classes.

    Args:
        source_path: Path to Python source file

    Returns:
        Dictionary containing functions, classes, and methods
    """
    try:
        source_code = source_path.read_text(encoding="utf-8")
        tree = ast.parse(source_code, filename=str(source_path))
    except Exception as e:
        raise ValueError(f"Failed to parse source file: {e}") from e

    result = {"functions": [], "classes": [], "imports": []}

    # Extract top-level imports for reference
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                result["imports"].append(alias.name)
        elif isinstance(node, ast.ImportFrom) and node.module:
            result["imports"].append(node.module)

    function_nodes = (ast.FunctionDef, ast.AsyncFunctionDef)

    # Extract top-level functions and classes
    for node in tree.body:
        if isinstance(node, function_nodes):
            # Skip private functions
            if not node.name.startswith("_"):
                result["functions"].append(
                    {"name": node.name, "args": [arg.arg for arg in node.args.args], "lineno": node.lineno}
                )

        elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            methods = []
            for item in node.body:
                if isinstance(item, function_nodes) and (not item.name.startswith("_") or item.name == "__init__"):
                    methods.append(
                        {
                            "name": item.name,
                            "args": [arg.arg for arg in item.args.args if arg.arg not in {"self", "cls"}],
                            "lineno": item.lineno,
                        }
                    )

            result["classes"].append({"name": node.name, "methods": methods, "lineno": node.lineno})

    return result


def generate_test_scaffold(analysis: dict[str, Any], source_path: Path) -> str:
    """
    Generate pytest-style test scaffold from analysis results.

    Args:
        analysis: Analysis results from analyze_source_file
        source_path: Original source file path

    Returns:
        Generated test scaffold as string
    """
    lines = []

    # Header
    lines.append('"""')
    lines.append(f"Tests for {source_path.name}")
    lines.append("")
    lines.append("Generated by IBM Bob Test Scaffold Generator.")
    lines.append('"""')
    lines.append("")

    # Imports
    lines.append("import sys")
    lines.append("from pathlib import Path")
    lines.append("")
    lines.append("import pytest")
    lines.append("")

    # Add project root to path
    lines.append("# Add project root to path")
    lines.append("ROOT = Path(__file__).parent.parent")
    lines.append("sys.path.insert(0, str(ROOT))")
    lines.append("")

    resolved_source = source_path.resolve()
    resolved_root = ROOT.resolve()

    # Import from source module
    # Handle files outside the project by using absolute path
    try:
        module_path = resolved_source.relative_to(resolved_root).with_suffix("")
        module_name = str(module_path).replace("\\", ".").replace("/", ".")
    except ValueError:
        # File is outside project, use stem as module name
        module_name = resolved_source.stem
        lines.append("# Source file is outside the project root; adjust this import if needed.")

    # Generate imports for functions and classes
    imports_needed = []
    for func in analysis["functions"]:
        imports_needed.append(func["name"])
    for cls in analysis["classes"]:
        imports_needed.append(cls["name"])

    if imports_needed:
        lines.append(f"from {module_name} import (")
        for i, name in enumerate(imports_needed):
            comma = "," if i < len(imports_needed) - 1 else ""
            lines.append(f"    {name}{comma}")
        lines.append(")")
        lines.append("")

    # Generate test functions
    if analysis["functions"]:
        lines.append("")
        lines.append("# Function Tests")
        lines.append("")

        for func in analysis["functions"]:
            lines.append(f"def test_{func['name']}():")
            lines.append(f'    """Test {func["name"]} function."""')
            lines.append(f"    # TODO: Implement test for {func['name']}")

            if func["args"]:
                lines.append(f"    # Function signature: {func['name']}({', '.join(func['args'])})")

            lines.append("    pass")
            lines.append("")

    # Generate test classes
    if analysis["classes"]:
        lines.append("")
        lines.append("# Class Tests")
        lines.append("")

        for cls in analysis["classes"]:
            lines.append(f"class Test{cls['name']}:")
            lines.append(f'    """Tests for {cls["name"]} class."""')
            lines.append("")

            if not cls["methods"]:
                lines.append("    def test_instantiation(self):")
                lines.append(f'        """Test {cls["name"]} can be instantiated."""')
                lines.append("        # TODO: Implement instantiation test")
                lines.append("        pass")
                lines.append("")
            else:
                for method in cls["methods"]:
                    if method["name"] == "__init__":
                        lines.append("    def test_instantiation(self):")
                        lines.append(f'        """Test {cls["name"]} can be instantiated."""')
                        lines.append("        # TODO: Implement instantiation test")
                        if method["args"]:
                            lines.append(f"        # Constructor args: {', '.join(method['args'])}")
                        lines.append("        pass")
                        lines.append("")
                    else:
                        lines.append(f"    def test_{method['name']}(self):")
                        lines.append(f'        """Test {cls["name"]}.{method["name"]} method."""')
                        lines.append(f"        # TODO: Implement test for {method['name']}")
                        if method["args"]:
                            lines.append(f"        # Method args: {', '.join(method['args'])}")
                        lines.append("        pass")
                        lines.append("")

    # Footer
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    pytest.main([__file__, '-v'])")

    return "\n".join(lines)


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate pytest test scaffold from Python source file",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate test scaffold
  python scripts/generate_test_scaffold.py --source ghostchimera/config.py --output tests/test_config_new.py

  # Dry run (print to stdout)
  python scripts/generate_test_scaffold.py --source ghostchimera/config.py --dry-run

  # Force overwrite existing file
  python scripts/generate_test_scaffold.py --source ghostchimera/config.py --output tests/test_config.py --force
        """,
    )

    parser.add_argument("--source", required=True, help="Path to Python source file to analyze")
    parser.add_argument("--output", help="Path to output test file (default: stdout if --dry-run, or auto-generated)")
    parser.add_argument(
        "--dry-run", action="store_true", help="Print generated scaffold to stdout without creating file"
    )
    parser.add_argument("--force", action="store_true", help="Overwrite existing output file")

    args = parser.parse_args()

    # Validate source file
    source_path = Path(args.source).resolve()
    if not source_path.exists():
        print(f"Error: Source file not found: {args.source}", file=sys.stderr)
        return 1

    if source_path.suffix != ".py":
        print(f"Error: Source file must be a Python file (.py): {args.source}", file=sys.stderr)
        return 1

    # Analyze source file
    try:
        analysis = analyze_source_file(source_path)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    # Generate scaffold
    scaffold = generate_test_scaffold(analysis, source_path)

    # Handle dry-run
    if args.dry_run:
        print(scaffold)
        return 0

    # Determine output path
    if args.output:
        output_path = Path(args.output)
    else:
        # Auto-generate output path
        test_name = f"test_{source_path.stem}.py"
        output_path = ROOT / "tests" / test_name

    # Check if output exists
    if output_path.exists() and not args.force:
        print(f"Error: Output file already exists: {output_path}", file=sys.stderr)
        print("Use --force to overwrite", file=sys.stderr)
        return 1

    # Write output
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(scaffold, encoding="utf-8")
        print(f"Test scaffold generated: {output_path}")
        return 0
    except Exception as e:
        print(f"Error writing output file: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())

# Made with Bob
